[package]
name = "julia_sets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl33 = "0.2.1"
# bytemuck = "1.11.0"
# glfw = "0.45.0"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"